### ISSUE TITLE
运行时异常

### ISSUE THREAD

**Issue by xtyxtyx** [xtyxtyx/sorry#1]
```
2018-02-25 01:31:36 - Errno::ENOENT - No such file or directory @ rb_sysopen - temp/197cb3a57353158ba1ca7f3f198a4ffd.gif:
        /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'                                                                                                                                  
        /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'         
        /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'                                                                                                                        
        /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'                                                                                                                                        
        /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'                                   
        /usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'                                    
        /usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'                                                                                                                                  
        /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'                   
        /usr/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'                           
        /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'                                                                                                                            
        /usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'                                           
        /root/sorry_own/src/sorry/cache.rb:31:in `add_file'                                    
        /root/sorry_own/src/sorry/make_gif.rb:71:in `render_gif'                                     
        src/sorry.rb:23:in `block in <main>'                                                             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'                   
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'                                                                                                 
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'                                                                                         
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'                 
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'                                                                                            
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'     
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'    
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'               
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'                          
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'                                                                                                   
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'                   
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'                                                                                         
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'                                                                                                             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'            
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'         
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'                                                                                                     
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'   
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'                                                                                                            
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'              
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'               
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'                                                                                                
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'                                                                                                
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/logger.rb:15:in `call'                           
        /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/common_logger.rb:33:in `call'                                                                                                             
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'               
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'               
        /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'                      
        /var/lib/gems/2.3.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'           
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'               
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'                                        
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'                                                                                                     
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'   
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'                                                                                            
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'                                                                                                       
        /var/lib/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'              
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'                                                                                                               
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'         
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'    
        /var/lib/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'    
```

**Comment by wdjwxh** [comment]
提示已经说出来了，没有那个gif
