### ISSUE TITLE
使用docker部署 调用接口报错

### ISSUE THREAD

**Issue by yongshengdev** [xtyxtyx/sorry#102]
已经安装了ffmpeg，docker以及服务也都部署了 调用接口报错
http://我的域名:4567/api/sorry/make
麻烦看下 谢谢了
2020-06-20 05:56:56 - Errno::ENOENT - No such file or directory @ rb_sysopen - temp/c9dcdfe4704b23f7671672d7c943d6a0.gif.ass:
        /app/src/sorry/make_gif.rb:57:in `write'
        /app/src/sorry/make_gif.rb:57:in `render_ass'
        /app/src/sorry/make_gif.rb:29:in `make_gif_with_ffmpeg'
        /app/src/sorry/make_gif.rb:87:in `render_gif_api'
        src/sorry.rb:98:in `block in <main>'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/logger.rb:17:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:231:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:224:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
        /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
Unexpected error while processing request: invalid byte sequence in US-ASCII
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/utils.rb:171:in `gsub'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/utils.rb:171:in `escape_html'
        /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb:106:in `h'
        (erb):186:in `block (2 levels) in pretty'
        (erb):185:in `each'
        (erb):185:in `block in pretty'
        (erb):157:in `each'
        (erb):157:in `pretty'
        /usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
        /usr/lib/ruby/2.5.0/erb.rb:876:in `result'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:82:in `pretty'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:31:in `rescue in call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
        /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
        /var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'

**Comment by yongshengdev** [comment]
作者能看到吗 很需要这个库 麻烦看下 谢谢了

**Comment by SilenceBurst** [comment]
大神，这个问题你还改吗？什么时候改呀？我有个功能用到这个，所以想了解一下，不是催你的意思。

**Comment by yongshengdev** [comment]
作者 买了服务器域名想用这个功能，麻烦有空可以改改吗 拜托拜托～
